CCE: Move existing /nearby processing to async task
department-of-veterans-affairs/health-apis-community-care-eligibility pull request #120
Opened 2021-03-02 17:05 UTC by taylorrassmannlibertyits

Moved nearby and other little bits of logic to nearby CompletableFuture thread.

https://vajira.max.gov/browse/API-5308

2021-03-03 21:26 UTC, as-va commented
Since you are modifying the response object inside the thread, we should ensure this is thread safe. Add these lines to the annotations of `CommunityCareEligibilityResponse`:
```
@Setter(onMethod=@__(@Synchronized))
@Getter(onMethod=@__(@Synchronized))
```

2021-03-09 14:50 UTC, as-va requested changes

2021-03-09 14:50 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +      return response
This doesn't set eligibility, but it should be `True` here.

2021-03-09 14:50 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +  private CommunityCareEligibilityResponse requestNearbyFacilityResults(
We do not want or need to return a CCEResponse object here - for two reasons:
1. It is unnecessary - we pass in the response object from the point of call, so the operations here take place on that object which is already in the scope of the caller so we don't need to pass another reference to it back out again.
2. We need to use the return type to handle the eligibility flag - Since the design has shifted to a tri-state eligibility flag (true/false/null), we cannot simply set true before threads and overwrite within as there are now two possible other values. So we need to return the eligibility determination from each thread and have the composer take the returns to set the final eligibility flag in the response.

Side effect: need to take out all response.build() lines inside this function. Do a single build once both threads have completed.

2021-03-09 14:58 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +      return response
ok, at first you said to not set global eligibility to true in the jira issue. I will make the change.

2021-03-09 16:58 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +      return response
Right, that was more just a heads up since we are changing how the eligibility reporting is done in my other comment so that this return spot didn't fall through the cracks.

2021-03-09 17:17 UTC, as-va approved these changes

2021-03-09 17:17 UTC, merged