Api 5309 pcmm request async thread
department-of-veterans-affairs/health-apis-community-care-eligibility pull request #121
Opened 2021-03-07 20:34 UTC by taylorrassmannlibertyits

https://vajira.max.gov/browse/API-5309

2021-03-09 14:53 UTC, as-va requested changes

2021-03-10 13:14 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +  private CommunityCareEligibilityResponse requestPcmmResults(
True, however, we also need to return `pactStatus` so this will need to be a little more complicated than a simple boolean return.

2021-03-10 13:15 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +  private CommunityCareEligibilityResponse requestPcmmResults(
In fact, I would argue, if only `pactStatus` is returned here, then an eligibility determination can be made in the `combinedFuture`

2021-03-10 13:29 UTC, as-va commented on community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/PcmmResponse.java
> +  public static final class PatientAssignmentsAtStation {
Shouldn't this class name be singular? The above list contains all the _assignments_, each instance of this class would be a single _assignment_.

2021-03-10 13:29 UTC, as-va commented on community-care-eligibility-tests/pom.xml
> -              <!--
Was this only used for testing or do you intend this to also be turned on in production?

2021-03-10 13:29 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +          if ("Active".equals(pactStatus)) {
Why don't we create an enum in the `PrimaryCareAssignment` class with the set of status strings so we don't hardcode this string here. Bonus: comparing the value of the enum could make the logic here easier to find the highest(/lowest) priority flag.

2021-03-10 13:31 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +  private CommunityCareEligibilityResponse requestPcmmResults(
I think we handle this thread the same way we do the nearby thread: set the `pactStatus` on the response here in the thread, do any calculations to determine eligibility (for this subpath), and return the Boolean eligibility determination to be combined with the other eligibility subflags in the thread combiner.

2021-03-10 13:43 UTC, taylorrassmannlibertyits commented on community-care-eligibility-tests/pom.xml
> -              <!--
Keeping it on for prod as well.

2021-03-10 13:44 UTC, as-va commented on community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/PcmmResponse.java
> +  public static final class PatientAssignmentsAtStation {
This also makes the looping logic in the controller more difficult to read as it is pulling `*assignments*` out of `*assignments*` - it would look more logical to pull an `*assignment*` out of a list of `*assignments*`.

2021-03-11 21:03 UTC, as-va commented on community-care-eligibility-api/src/main/java/gov/va/api/health/communitycareeligibility/api/PcmmResponse.java
> +    List<PrimaryCareAssignment> primaryCareAssignment;
Should do the same here as above - have the class name be singular but the variable name plural and remove the localName annotation to be consistent.

2021-03-11 23:14 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +                response.eligible(null);
Should we leave this as is then and set in the next task? 

Otherwise, I propose the following logic with questions:

- If either result false then false? Wouldn't this change what happens with the geocoding results?
- If both are true then true? This one works the best
- If one is null, should eligible be null, or false?

2021-03-12 03:16 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +                response.eligible(null);
This is really supposed to be covered by 5310 so I'm fine with taking all of this logic out, but I don't want to commit a wrong version with the plan of fixing later. So, all or nothing.

It should go something like:
If ANY are FALSE then return FALSE
Else if ANY are NULL then return NULL
Else (ALL must be TRUE here) return TRUE

2021-03-12 12:34 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +                response.eligible(null);
So can you say this PR is good to go, and then we confirm this logic for 5310?

2021-03-12 13:12 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +                response.eligible(null);
Yes, the rest of this looks good now, but as I said yesterday I'd rather take this result calculation out entirely and do it correctly in the next pass than to leave this incorrect version in place.

2021-03-12 15:28 UTC, as-va approved these changes

2021-03-12 15:29 UTC, merged