Api 5310 merge pcmm and nearby task results
department-of-veterans-affairs/health-apis-community-care-eligibility pull request #122
Opened 2021-03-12 18:26 UTC by taylorrassmannlibertyits

https://vajira.max.gov/browse/API-5310

2021-03-15 14:23 UTC, as-va requested changes

2021-03-15 14:23 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +              if ((pcmmRequestResult != null && !pcmmRequestResult)
There is nothing wrong with this code and it accomplished the desired behavior correctly. That said, it is unfortunate this has to be four checks including six terms (if you count the nulls) in multiple sub groups to do a simple boolean comparison (feature of the language).

I think I would have a slight preference for 

    if (Boolean.FALSE.equals(pcmmRequestResult) || 
        Boolean.FALSE.equals(nearbyRequestResult)) {

as this cuts the complexity of the statement back down to the actual intent of the check without the housekeeping of the embedded null checks or the nesting of parenthesis to accomplish the task.

Not requesting a change here, just pointing out a different stylistic option.

2021-03-15 14:23 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
I don't think this works this simply. `get` raises multiple checked exception types that you aren't handling because the `SneakyThrows` is masking them, but if you actually trigger this timeout, the future doesn't just return, it throws a `TimeoutException` which isn't being caught.

2021-03-15 14:23 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
You could add a handler here for the `get` timeout, but instead I think I'd pass responsibility back up the the original Futures and add a `completeOnTimeout` registration where they are defined. That can set up a timeout on each thread _and_ specify a default value to return in case the timeout is triggered so that the combining Future can still function as designed with no changes.

2021-03-15 14:39 UTC, taylorrassmannlibertyits commented on community-care-eligibility-tests/src/test/java/gov/va/api/health/communitycareeligibility/tests/AdvancedSearchIT.java
> +    assertThat(response.eligible()).isTrue();
One of the main reasons why I didn't want to make those changes for the previous PR. Will update in the next comment.

2021-03-15 14:41 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
Even if the exception isn't caught, isn't that a good thing? Don't we want to fail on a timeout?

2021-03-15 14:46 UTC, taylorrassmannlibertyits commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
If either thread has a timeout, shouldn't we fail the call? I disagree here. I think the timeout should be in the combined call.

2021-03-15 14:50 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
There should be a new test to cover the expected behavior when a timeout occurs.

2021-03-15 15:17 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
In the most aggressive approach you could say we should return a `4XX` error to the caller (with reason message), but this would be a fatal condition for the request handler which I believe would return a `5XX` error response which seems too extreme a response.

2021-03-15 15:20 UTC, as-va commented on community-care-eligibility/src/main/java/gov/va/api/health/communitycareeligibility/service/CommunityCareEligibilityV0ApiController.java
> +    combinedPcmmAndNearbyResultsFuture.get(10, TimeUnit.SECONDS);
I can see a logic for that argument, but we've already been instructed that if we do not get a response from PCMM to handle that by setting PCMM eligibility to `null`. It seems to me that the PCMM call not returning is a sub form of the 'failure to get PCMM results' handler and should be handled the same way.

2021-03-16 15:39 UTC, as-va approved these changes

2021-03-17 12:34 UTC, merged